name: Dependabot

on:
 pull_request:
    branches:
    - master

jobs:
  run-npx-my-precious:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Checkout branch
        run: git checkout ${{ github.head_ref }}
      - name: Set remote url
        run: git remote set-url origin https://x-access-token:${{github.token}}@github.com/${{github.repository}}.git
      - name: Configure email and user name 
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Dependabot alert"
      - name: Run npx my-precious and build archived-packages
        run: npx my-precious
      - name: Commit changes to master branch
        run: | 
           git add .
           output=`git commit -m 'archived package'` && echo "::set-output name=OUTPUT::$OUTPUT"
      - name: Push changes to branch
        if: ${{!contains(steps.main.outputs.OUTPUT, 'up to date')}}
        run: git push
    
  
